name: Open Unsigned App and Screenshot

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: macos-13

    steps:
      - name: Download ZIP file
        run: |
          curl -L "https://github.com/OpenBubbles/Mac-Hardware-Info/releases/download/v1.2.0/Mac.Hardware.Info.zip" -o Mac.Hardware.Info.zip

      - name: Extract ZIP file
        run: unzip Mac.Hardware.Info.zip

      - name: Disable Gatekeeper (allow unsigned apps)
        run: sudo spctl --master-disable

      - name: Launch the app and wait
        run: |
          # Find the first .app bundle in the current directory
          APP=$(find . -maxdepth 1 -name "*.app" | head -n 1)
          echo "Launching app: $APP"
          open "$APP"
          # Wait 2 seconds for the app to launch and display its window
          sleep 2

      - name: Take screenshot of the desktop
        run: |
          # Take a screenshot without the sound; adjust options if needed
          screencapture -x screenshot.png

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot.png
