name: Open Unsigned App and Screenshot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: macos-13

    steps:
      - name: Download ZIP file
        run: |
          curl -L "https://github.com/OpenBubbles/Mac-Hardware-Info/releases/download/v1.2.0/Mac.Hardware.Info.zip" -o Mac.Hardware.Info.zip

      - name: Extract ZIP file
        run: unzip Mac.Hardware.Info.zip

      - name: Disable Gatekeeper (allow unsigned apps)
        run: sudo spctl --master-disable

      - name: Remove quarantine attribute from the app
        run: |
          APP=$(find . -maxdepth 1 -name "*.app" | head -n 1)
          echo "Removing quarantine attribute from $APP"
          sudo xattr -r -d com.apple.quarantine "$APP"

      - name: Launch the app
        run: |
          APP=$(find . -maxdepth 1 -name "*.app" | head -n 1)
          echo "Launching app: $APP"
          open "$APP"
          # Wait a few seconds for the app to launch
          sleep 3

      - name: Bring app to front using AppleScript
        run: |
          APP_NAME=$(basename "$(find . -maxdepth 1 -name "*.app" | head -n 1)" .app)
          echo "Activating app $APP_NAME"
          osascript <<EOF
          tell application "System Events"
            set frontmost of first process whose name is "$APP_NAME" to true
          end tell
          EOF
          # Give extra time for the window to come forward
          sleep 3

      - name: Take screenshot (should capture the app window)
        run: screencapture -x screenshot.png

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot.png
