name: Open Unsigned App and Screenshot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: macos-13

    steps:
      - name: Download ZIP file
        run: |
          curl -L "https://github.com/OpenBubbles/Mac-Hardware-Info/releases/download/v1.2.0/Mac.Hardware.Info.zip" -o Mac.Hardware.Info.zip

      - name: Extract ZIP file
        run: unzip Mac.Hardware.Info.zip

      - name: Disable Gatekeeper (allow unsigned apps)
        run: sudo spctl --master-disable

      - name: Remove quarantine attribute from the app
        run: |
          APP=$(find . -maxdepth 1 -name "*.app" | head -n 1)
          echo "Removing quarantine attribute from $APP"
          xattr -r -d com.apple.quarantine "$APP"

      - name: Launch the app and wait
        run: |
          APP=$(find . -maxdepth 1 -name "*.app" | head -n 1)
          echo "Launching app: $APP"
          open "$APP"
          # Wait 2 seconds for the app to launch
          sleep 2

      - name: Bring app to front using AppleScript
        run: |
          APP_NAME=$(basename "$(find . -maxdepth 1 -name "*.app" | head -n 1)" .app)
          echo "Bringing app $APP_NAME to the foreground"
          osascript -e "tell application \"$APP_NAME\" to activate"
          sleep 2

      - name: Take screenshot of the desktop (should include the app window)
        run: screencapture -x screenshot.png

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot.png
